# 1. Definindo a rede interna
networks:
  gdash_network:
    driver: bridge

# 2. Configurando os serviços
services:
  # 2.1 Serviço MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gdash_network

  # 2.2 Fila de Mensagens (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gdash_network

  # 2.3 Serviço de API (Nest.JS)
  api_service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_gdash
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://rootuser:rootpass@mongodb:27017/gdash?authSource=admin
      RABBITMQ_URI: amqp://rabbituser:rabbitpass@rabbitmq:5672
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - gdash_network

# 3. Configuração de Volumes
volumes:
  mongo_data:
  rabbitmq_data:
